title = "Atelier Horizon Verre"
baseURL = "https://atelierhorizonverre.fr"
tags = ["landing"]
languageCode = "fr-FR"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "ahv"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "Atelier Horizon Verre"
  author = "Atelier Horizon Verre"
  description = "Site en construction"
  logoBig = "/images/logo-ahv.png"
  logoSmall = "/images/logo-ahv.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/osprey.png"
  email = ""
  googleTagManger = ""
  customCSS = false

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = ""

  # Lazy loading with lazysizes
  lazyloading = true

# [[menu.main]]
#   name = "About"
#   url  = "/#about"
#   weight = 1
